=== MapekaJR/Lenguaje-de-marcas/DTD/1dtd.dtd
<!ELEMENT note (to,from,heading,body)>
    <!ELEMENT to (#PCDATA)><!--#PCDATA es como un string vaya un cuadro de texto -->
    <!ELEMENT from (email, nombre)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT heading (#PCDATA)>
    <!ELEMENT body (mensaje, fecha)><!--Dentro de body hay mas etiquetas por lo cual se meten en el parentesis-->
        <!ELEMENT mensaje (#PCDATA)>
        <!ELEMENT fecha (dia, mes, anno)>
            <!ELEMENT dia (#PCDATA)>
            <!ELEMENT mes (#PCDATA)>
            <!ELEMENT anno (#PCDATA)>

=== MapekaJR/Lenguaje-de-marcas/DTD/1dtd.xml
<?xml version="1.0"?>
<!DOCTYPE note SYSTEM "1dtd.dtd"><!--Hay que unir en esta etiqueta el documento dtd
                                    en el otro no hace falta poner nada -->

<note>
    <to>Pedro</to>
    <from>
        <email>a@a.com</email>
        <nombre>Angela</nombre>
    </from>
    <heading>Recordatorio</heading>
    <body>
        <mensaje>Este es el mensaje</mensaje>
        <fecha>
            <dia>12</dia>
            <mes>Marzo</mes>
            <anno>2022</anno>
        </fecha>
    </body>
</note>
