<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE declaraciones [
    <!ELEMENT declaraciones ((consonante | tipo_de_dato | variable)+)>
    <!ELEMENT consonante (#PCDATA)>
    <!ELEMENT tipo_de_dato (#PCDATA)>
    <!ELEMENT variable (#PCDATA)>

<!ATTLIST consonante valor CDATA #REQUIRED>
<!ATTLIST variable tipo CDATA #IMPLIED>
]>
 <declaraciones>
     <consonante valor="3.131692">PI</consonante>
     <tipo_de_dato>tipo de datos</tipo_de_dato>
     <variable>area</variable>
     <variable>longitud</variable>
 </declaraciones>