=== MapekaJR/Lenguaje-de-marcas/DTD/futbol.dtd
<!ELEMENT futbol (equipos)>
    <!ELEMENT equipos (equipo)>
        <!ELEMENT equipo (nombre, copas, jugadores, equipacion, partidos, estadio)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT copas (#PCDATA)>
            <!ELEMENT jugadores (pichichi)>
                <!ELEMENT pichichi (nombreP, fechaNacimiento, goles, tarjetas)>
                    <!ELEMENT nombreP (#PCDATA)>
                    <!ELEMENT fechaNacimiento (#PCDATA)>
                    <!ELEMENT goles (#PCDATA)>
                    <!ELEMENT tarjetas (amarillas, rojas)>
                        <!ELEMENT amarillas (#PCDATA)>
                        <!ELEMENT rojas (#PCDATA)>
            <!ELEMENT equipacion (primera, segunda)>
                <!ELEMENT primera (#PCDATA)>
                <!ELEMENT segunda (#PCDATA)>
            <!ELEMENT partidos (jugados)>
                <!ELEMENT jugados (ganados, perdidos, empatados)>
                    <!ELEMENT ganados (#PCDATA)>
                    <!ELEMENT perdidos (#PCDATA)>
                    <!ELEMENT empatados (#PCDATA)>
            <!ELEMENT estadio (nombreE, capacidad)>
                <!ELEMENT nombreE (#PCDATA)>
                <!ELEMENT capacidad (#PCDATA)>

=== MapekaJR/Lenguaje-de-marcas/DTD/futbol.xml
<?xml version="1.0"?>
<!DOCTYPE futbol SYSTEM "futbol.dtd">

<futbol>
<vacio/>
<noVacio>Dato</noVacio>
    <equipos>
        <equipo>
            <nombre>Betis</nombre>
            <copas>0</copas>
            <jugadores>
                <pichichi>
                    <nombreP>Joaquin</nombreP>
                    <fechaNacimiento>1980-10-10</fechaNacimiento>
                    <goles>100</goles>
                    <tarjetas>
                        <amarillas>1</amarillas>
                        <rojas>0</rojas>
                    </tarjetas>
                </pichichi>
            </jugadores>
            <equipacion>
                <primera>blanco y verde</primera>
                <segunda>azul y blanca</segunda>
            </equipacion>
            <partidos>
                <jugados>
                    <ganados>100</ganados>
                    <perdidos>10</perdidos>
                    <empatados>50</empatados>
                </jugados>
            </partidos>
            <estadio> 
                <nombreE>Benito Villamar√≠n</nombreE>
                <capacidad>60000</capacidad>
            </estadio>
        </equipo>
    </equipos>

</futbol>
